### ISSUE TITLE
Stuck at "Detecting Languages"

### ISSUE THREAD

**Issue by dlanz** [briandiloreto/AtomicViz#2]
Hi, I'm running into issues when selecting a series of PHP files to create a graph for. All I get is a VSCode notification in the bottom right indicating it is "Detecting Project Languages". No graph is presented, either in the main editor area or in one of the sidebars. Same behavior regardless of whether I have the "Show In Sidebar" or "Show In The Editor Column Two" settings enabled or not.

I'm assuming I do not have the proper PHP language pack installed. The closest I could find was: 
[https://marketplace.visualstudio.com/items?itemName=icatalina.php-extension-pack ](https://marketplace.visualstudio.com/items?itemName=icatalina.php-extension-pack )

Is PHP supported and is this the proper language pack?

**Comment by briandiloreto** [comment]
Hi @dlanz. Thanks for the question. PHP should work.

First of all, did you see the prompt to select the language of the files you want to graph. See my screenshot.
Whenever there are files of different languages in the directory you selected (e.g. PHP and HTML files), then you have to choose the language you want. Probably I should ignore some languages like HTML to avoid this step.

![atomicviz_choose_language](https://github.com/user-attachments/assets/79df6351-d2c2-49b6-9915-7ffb365cbf1b)

Also, looking at the PHP language extension pack you linked, I see it has only about 10K installs versus the 5 million installs of the most popular PHP language extensions for VS Code. Is there a reason to choose this particular PHP extension?

https://marketplace.visualstudio.com/items?itemName=xdebug.php-pack

Let me know if this helps.

**Comment by briandiloreto** [comment]
Thanks for the feedback @dlanz.
After a little testing, I realize that you are right, the extension will not properly graph PHP function dependencies. The extension did create a graph for me, but it does not show arrows for the function calls.
Sorry.

![atomicviz_php_fail](https://github.com/user-attachments/assets/a9fb7e4e-9f9d-4358-a340-099bfefefb7e)

For the record, I found that none of the PHP extensions for VS code actually provides call hierarchy information, which is what AtomicViz needs to create the graph. Perhaps in the future they may provide that information.

Regarding the graphs for C code, can you help me to understand how you tested "from a WSL Ubuntu instance"? When using the Windows Subsystem for Linux, doesn't that apply only to the linux shell?

Thanks!

**Comment by briandiloreto** [comment]
Thanks for the education @dlanz. I didn't really understand that you could do remove development using WSL. Pretty cool.

Honestly, I'm not sure why AtomicViz wouldn't work when running under the WSL environment. It doesn't seem like that should make a difference if VS Code (and its extensions) are the same in the WSL environment.  I will try to figure this out at some point in the future.
